apiVersion: v1
kind: Service
metadata:
  name: {{ include "random-jdr.backend.fullname" . }}
  labels:
    {{- include "random-jdr.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "random-jdr.backend.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "random-jdr.frontend.fullname" . }}
  labels:
    {{- include "random-jdr.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "random-jdr.frontend.selectorLabels" . | nindent 4 }}
