---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: llm-credentials-staging
  namespace: random-jdr-staging
spec:
  encryptedData:
    llm-api-key: AgCKzyDR0VgYo/85q/3LuPexeiL/LErl3coPy/t9b5SEV2PYVxOHQ8n189FLJg2lzm042uIkV5A722pnR2/GhcZrZ9mHVw/PgklTCT8vwmJF291FC6KrXwWt+kWLOGc6dioOh809oXl4RHtSgx2mnW5MCoclE9WcLcw2/RGajgR+6qt7XLwDAQqH6P8kh5AtampaK8MpSif4zyf83yR3G0yJKyErpaXNnLpCLfwF/MVD1PMVK5xZfQOx8+CdVX8iFOUvczEo997+ya7x2CavmzNVgvhCrhpXpDxF036HbV0KSMkeu3DoYFsXgQRlhO7OfXY8nKjq4jEpfbbNbw9t1VXJQPoCXfxkrF4fNhG0HTD8Y2qLNsjQA3drX82NdvOEUMPFvV8bJ/OSeGdzNb4FRSeejjYTjsrQ7+n1bTO/W9lR91hURPtFMD47dqQ+A1UElgJCWWjAU/Ie0KvQoS09eFr9HjSyrai+Bnrz69+ePRu5OE0y+FmayNGrAuLMJlmQHLAS7DxpgxSeUQSbOi3hv95Te3sMKcgsxGj9yjGvGner7FvJoK9KbianpEYRwkl3xxdlJ4lX1+h19gMFFGiLTF+ZW78JNLy97iUasJSv5I93d8iHdLEnECIJpEv2MfOHF7bpGbQDdIydUyHCXnPtmwy7ng0j2bKzfwOe+6tD6kKx/5eSSwbxSEprL9mtRuUba5/fnvXHkALDb/maRtny0QK850KDK/Rsuj+MekNMuLiFig==
  template:
    metadata:
      creationTimestamp: null
      name: llm-credentials-staging
      namespace: random-jdr-staging
    type: Opaque
