---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: llm-credentials-staging
  namespace: random-jdr
spec:
  encryptedData:
    llm-api-key: AgBnF31VLrqJvLVr7hJGa0MKsOeMGkFRhtpINgairl4T7+kIGhdZqd3VAI+9PlOnmR1UEd1IJpwy33zqi5sF6VUraOqZlWZjNFJ6BZmcSkjbwseAx7A9GAKwF3b4+S0r8vtUL0UdQ5xUBsZMnPm4i4koBDKoGDRV/Tb6f4bkEk6R5S6rjX1av4WW3Bb/kHgqTvlz4zFa/su20JS6FXxseXPZFI7uzAuXTtuMP+6qWmMAdKGxIgRD1FHrEdDSa9cGGFrVxRl/nwQGEE3NpMgZbuEbqULhNGuXw85EonxeiokYxlBTXs6VRlrvZC4A4zpmzkhdFXVl5mynwIiMfGUsEhgmAu4Kb53L/kf4fNSA+ZpkdUZnWsz4TVLaYCrGUXbr3s7Mkc0woG6g5zDRi7T8TYdc69YYAXDr9z4geGlrdGtfDVHQmgKrFauhGlZPQkuaMIeg7hDUAj0zXKvw2Sxy+xRX9sjbzAw6c4mVAy61mcc1sjq8VMoXqmyRC+9/7nbaTa4wsLmUiIbDbyjqDZaTVsaLaG1UBzbhGGWN5vDBVgL05iPSOngHsWBM4r7+GQ1Vz4unZuHGhmF2wd/HqcHCbzHGeqxwPpKyAjFX1nTjNil07S8tpCJz635dRHBwDMypzN425F5FQkgyLKaOyNwrWnWh9TKqTxxmfT2PKDfP5ndEaX+MO/oow2udjOkWEU2BxYMRWa1dO3euV9qOjhAhcezWFgcrlJyX3LuZYfWT2cEicw==
  template:
    metadata:
      creationTimestamp: null
      name: llm-credentials-staging
      namespace: random-jdr
    type: Opaque
