{{- if eq .Values.global.environment "production" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: random-jdr
spec:
  encryptedData:
    password: AgBrcPqb/OYmDAU1RWAOhdiYESkXx9cUeIAc8VJo+R4vVsxUAIvMxpXn5khIEaI+RhMzYTG51FEdsmu1SLATYebw+7AeAQrA5DEitzUapv7lXKI8M3aSuWiNAN8zKtBZXqOVN67Atm34+3Y5V2Sv8JekOoa9anHFuaA/RSLOAtGlKxYmDcPWj3rp/p/LlYD5WSxxCzuhmIRbZkyyFh+RipdkN6LvcGHMpSZFMGD8gNCXjtCmH6T+TGJaYQZ/85oj7taAEpOjqcbv/4AOziF+72WVSxV9MlVpprU5rmsdYxr7XAYfxgUkSvsy8Z6tQG4LZMh6zUKPDEcFlf9q/WUDo5ABuesq3B+68Bc6Uuly2Agp29izyEC4Po1tCY5GzL9lhJasnvn9elKwKGg1paR1aUJ4QzMuUq4DnPcvagtrbUl2PY6TWOS1Gbf01fTSVt8uyT3bM1sD+KUEZoFiGv/QhI3zMgqBk2Y7GJ9Ar3oXj7zhLdYAsu4KXS4/3zJhyYL7FWahdRjcHXyOGKT25HWaKINkcTo5lN2g3+0hRzLv0rbTHnoxwT/f9rDXsPEHtoStp6qLG18SQHXFxP7pa4pBPDOS3vunh1WVRF68+5Uw8Rtb+XAED4y+P3lihmywpzxyl3ZgZeE+elmq/eBTrWAbXCgheDVHI9OVz+I6hkppLCpMgkhGpO4QMbiQGk/4eZuwrZngrFTptkisf19Uf6G7AfUX1VqObg4hQlaKdpRdPw==
    postgres-password: AgAWlpepNGCnn9rx7JZG5qGPev+lDtQJgTrTowLEa+/gPp+cILYgKwWBoxRmCy2gXerA/yBtqSwgtnM1iqosAiEQt8BHdbjMw707/JWQ+KnG1WEwNCZMkhb52yr/83TiuLqSFSCDpNNRzVtmGLxfvPFbJJBgOoIpr8emQVIOMmZV0llFGvRwHuX9ICkfJ6bsmScrYIjrye992yj5oiJAJRkvu/pHm8c8r4mrPAXOU9unscx3t3hT40UOuz+vLrPf6zPyh1U/F4+00cSSL2LlLOUfj/CR4ckGzjELo9Ezm0fcsIPaI8XJft85nTLUh1X2UmVdlAbvon8x4UqvpFUIsUXuubVSB7n9XHVusIyTo7PoYzZBG45rLvfp8Sq37ShGLnLNHnV9A4Do4MT0VfTo9csYyM1zvbljiepKcsep+31P2j1jjy2cD++mIJAAzLUsrkQFBPiEjQbNq5mJmULVMTlCqOiGyeW6zRWVwmrLY/O/YbzrhKZx7fkppwQmJDfmU3PHbp5tHXdNMbrU9Thg/5bciK1WEvOeKcNm44KK4vEdx9GYrxiVojKMHL5sefalsaQ5JiuiZluVz+GctSD7TFF2XCEARcsHs/RN2oU2lB9B2GLxcNimtXnKIJI7OuoC/0k9MBSMk92JkG2Q7HIFfxXILm/7uv7CVqyRO+mjA9q7KPi1rud3fxt33B46WWfEs/mHT+1m9oPB+EdjXw32YxY47k9W+Rz0YzKVWV7Nuv3pTguuKNo=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: random-jdr
    type: Opaque
{{- end }}