{{- if eq .Values.global.environment "staging" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials-staging
  namespace: random-jdr-staging
spec:
  encryptedData:
    password: AgBLGJNHJd8vgJTR9m8eyyGyy8a0FfJROCQLlQNoOof6lhEy4GDuZjKZVw1dTHFJMOQ6uex42xN4+lwddC+c0Hw1ug159fu/wyInB0pyqs6K4qeJonb6SWjdt9RfP6XnHdLhhV7Ra3gEc5UHj+hphLqh/hx1qNcHrks0krz2MSGu76nE+EwhWgPqPMd+OSm4o7NwlAJl6YCl9f4XW8i17uh3yoiERFcM4YM5MxdOqk78gQ2sr9MdrwDpZ17aemrqlcCSGi7Y31wwN90RCeNHGZJq2wj1KO21jvfXKg/wecxt/kzKKpQRBxow6oQf/ZMesRQbHYBvb3+PjvasEos7LnMeIVlsY8QyMXj+p4EVfd7O+xdkUSshW1Sm8Qc3fdYVdS0ELyqgn3vdNw8Lojjg2Y4e9hd+7bwnRt60YbVLr0HXefomF+aZA+us/qgKuh44YYHJH3DM2g2yBt51leVusx8WsXBT1+C04zzUQQWv5JQnuZQ8ZFZO0LiA+Rblozp8vDaAGEQKxMSIcrxiBTlmK7yMfuEV8jIGfE0slcxWdF/ZOa4lcNjsaaOiMmHvN/tGaZgKtWw6IvSmHM6lt+pfMZjMOjmJOhv6zce7brTP//wsWSh4MQF3OtXVT3SUogHb0fFIn7koHLZs3vNPUaSXTp0vseMoXYETqxjwKaf8SXa7dXalCXLRW6ALaj5Lt5L5bcs9BAqh8mEN71tPO2yHCtdUlM5R1B9LuWYdYGBysQ==
    postgres-password: AgBFUejdNRI7Mk8yt8ZZl2tQxNNY8t3MPVy13Ad9sCqTMKPfFx7YNlyU5QqgJUstcKykr4nkJqVc1hsoUv9NW227mLdRAPHYP5WsMJ2g9xMwfhKkfT0b90Hwg00jV9lfeCsRCvmEgR0Xe4Cx7m0uHUc+1FZhQ1DCOtKh9vlvOZfI1Dm4HBrZDs6NG0pbxh8YfHXUbKuanDAF5x/t1BLxC5CrR0md55mFfVgDKHqVwnnuoLF/Ta51KiBj2GJv6i+e/0sqWvBlwmtLi/mLRjhDBNUdc95BN36/qOmOut9S/+S80QUrl9MFVdgEeT/tpyjCPPPqBpyIEjhpdmNO0J1Bd2M3NuFnOaZhnZDzSb2Zr+Me/CgtLv6sodnMkAGBSjzpAMQDOC7Lwgu/D4tDW94bHRVVbQV1yEEwJX2MNv6nteEwIHJn499ONAD2EEVDzGt9lQK1vGjSdXrY7jxXwKIW5GxW76eqbce9MxlqdSG4vSS3/8bneXLgtlWxGAWW2KEBDw4QTw9qigwAD0kGfAznLpcsyd64x9IvUXJmVvwPRbaniikBSxgTGjjVmfeKQUKwhoJ4skaKYdT3Jdu38zVFtlHhjy/XgNfBAgv7OoJSYa55BWya79lS7Jajue1vcsKjn+QOZ2BwZl6I0wWn84z7zjNdfWECvi+r4Wo9bTMYKTyzpiEMcM17lY/dAP+nIKrXHP9AfldSMWAIv/wILXCg1BpucQMihnJXJmkn5jzZu2t9BkLJNH0=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials-staging
      namespace: random-jdr-staging
    type: Opaque
{{- end }}