---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials-staging
  namespace: random-jdr-staging
spec:
  encryptedData:
    password: AgBmRpwygkXrfhlowVdDBM7lsnCQYfz0r+TZAPXtqWVN3HVLp9mZefVBmWX/ZV6e7GoSOuzsP/kBSLCaaao48xX/aHY1MvOBO9hMP74Rn77gFS4Vkh3jFqW/1isa3Zn3Z2Qou1N2HKnByLdQYhqAaJp1TnMbNFy7eHQ8FdeMxXT9WWllFj0N5Z67zW8SXAnqiHDO7ux6uOSQUBIf6qYLx69yt7QTsiBOVmURAfsP9UF5i80WW8yop29jxADj3gyWUp48oEy7CNh4Qt1+N5j5VG3TAXoYgtkD7Bjpcj7/QJk9Nitpdbb18dA2hVp01vrL9fSfnQa4hS4fQR0BHW+sPlCRf0WM4aKTm/5qS7MssHbc41H/ZNrQgb6HGwwcLcmFiCD7OP/uaom6pAeaqTmc8tOyLhdyWkA7wHmh+7dV9vK6GLZSkIx3BK/tEGmCEkMuQlUiXHRiRmbQD012vZ8eW58RYRJR46b8V+JVYvqBm41mvWtwLozbYC7K0KS1vUCPzMWjd6rZRkqKLW+TrojYuyk8w6+6/dAYjIMShkGWLrfa4F3C7VwQ8YbDaErUWEMz/Rov8wcRR9KbRcgQ2F8WRh9FcZq42/G2NS8nxvz32XMDfQGwM7ir7R0j46TV+vILvgxMBdzD+uCQJ92u2s8godSACZIKc9ZK3QgWrF96NSRj+m0+amOQcBw3xnhMbuGNz01HwSASiZBSD4ccRQveSro0usMZdzFu6f3to1zvdg==
    postgres-password: AgASoeNc2KPOWTX/qVCB2h+JXN6doNCteA3t2pqg5oCetd9qUBTuEQdSJvq6nRvRl6qC3XE9Omk9FKaI/U7/6rJwIbOwsoeHZoIEvwDTEFVq/eUzawz5VMEkizRhAZeEEra7+IhP63LR8UzWptpTTW71PGlvPSAR7LVOMz3670qNZUtoXbWjg6U6+fwhb4D785f0arNb4Hc3A9B4NaEmtV8mZtrpFJsbZwRoXXOd3lq6GlU663md7LRhd/SbxriHKr6vQvvRW1bVo5sOxS7MCbpsjotJElcuCc4b0bQDlvHOYFvYhZTGp8RGF4gREfMOEsPzjUYEcFvd2JcVFZrcH5hOJEazKCSCOKZyKEkffC7by6ofvohG4CG23YfPPBidnQQPVbxrtvwok8vcimqCvD7atx1pBg4Kg8NfDeTT7L47XnrntYg9ZIi4lgV5o51Zc/BNHB2Ze/HbeneDqSF82vTMRzFU6xyisaGYONXk+YDs6jtyFYwLan+Vusiisf6vQNb8xLtKaUoXzPOry5KVwjIZWZexd46zUFaaDdLeTQanjnRCyTU78caxDkR6owvqHqDHsh5FTLuV3Sf5/n3SQeUvaKJ9mVDi44YSJ5xbML/NeG8v9RIfa42lLUxzfAF9Jxp+l83ICXFHlvRA/m1JNarsvl5vQK8Nl53wecItDZIa74qwV/zb/V+DkzfMcCSTO1kd2yDFXxCagllvD5biug/620gVopoWRSjW6OALOJqrpmdyDVI=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials-staging
      namespace: random-jdr-staging
    type: Opaque
