apiVersion: v2
name: random-jdr
description: Helm chart for Random JDR
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: postgresql
    version: "15.5.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled