global:
  appName: random-jdr
  environment: production
  imagePullPolicy: IfNotPresent

backend:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  env:
    - name: POSTGRES_HOST
      value: random-jdr-postgresql
    - name: POSTGRES_USER
      value: leogout
    - name: POSTGRES_DB
      value: random-jdr
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    - name: LLM_API_KEY
      valueFrom:
        secretKeyRef:
          name: llm-credentials
          key: llm-api-key

frontend:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

ingress:
  enabled: true
  hosts:
    - host: random-jdr.leogout.fr
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: random-jdr-backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: random-jdr-frontend
              port:
                number: 80
  tls:
    - secretName: random-jdr-tls
      hosts:
        - random-jdr.leogout.fr

postgresql:
  auth:
    existingSecret: db-credentials
    username: leogout
    database: random-jdr
  primary:
    persistence:
      enabled: true
      size: 1Gi
