global:
  appName: random-jdr
  environment: production
  imagePullPolicy: IfNotPresent

backend:
  enabled: true
  name: random-jdr-backend
  nameOverride: random-jdr-backend
  image:
    name: "random-jdr-backend"
  replicaCount: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
#  env:
#    - name: ENV_VAR_EXAMPLE
#      value: "production_value"

  service:
    type: ClusterIP
    port: 8000

frontend:
  enabled: true
  name: random-jdr-frontend
  nameOverride: random-jdr-frontend
  image:
    name: "random-jdr-frontend"
  replicaCount: 3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 80
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  metadata:
    name: random-jdr-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: random-jdr.leogout.fr
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: random-jdr-backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: random-jdr-frontend
              port:
                number: 80
  tls:
    - secretName: random-jdr-tls
      hosts:
        - random-jdr.leogout.fr

serviceAccount:
  create: true
  name: "{{ .Release.Name }}"

postgresql:
  enabled: true
  auth:
    username: "postgres"
    password: "postgres"
    database: "random_jdr"
  primary:
    persistence:
      enabled: true
      size: 8Gi

image:
  repository: "ghcr.io/leogout"
  tag: "v1.0.0"
