global:
  appName: random-jdr
  environment: production
  imagePullPolicy: IfNotPresent

backend:
  enabled: true
  name: random-jdr-backend
  nameOverride: random-jdr-backend
  image:
    name: random-jdr-backend
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8000

frontend:
  enabled: true
  name: random-jdr-frontend
  nameOverride: random-jdr-frontend
  image:
    name: random-jdr-frontend
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: nginx
  metadata:
    name: random-jdr-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

serviceAccount:
  create: true
  name: "{{ .Release.Name }}"

image:
  registry: ghcr.io/leogout
  tag: v1.0.0
