name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      github_token:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v4

      - name: Se connecter au registre Docker de GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Construire et Pousser l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ inputs.image_name }}:${{ inputs.tag }}
          file: ${{ inputs.dockerfile_path }}
