name: Backend CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Go into the backend directory
        run: cd back/

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run lint
        run: uv run ruff .

      - name: Run type checker
        run: uv run mypy .


  backend-tests:
    needs: [ backend-lint ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Go into the backend directory
        run: cd back/

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Run lint
        run: uv run ruff .
