name: Reusable Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Connecting to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building and pushing frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:front"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Building and pushing backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:back"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/random-jdr-backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
