name: Build and push to registry then deploy to cluster

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

env:
  HELM_CHART: ./helm

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'front/**'
          backend:
            - 'back/**'

  build-and-push-frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Connecting to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building and pushing frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:front"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:buildcache,mode=max

  build-and-push-backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Connecting to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building and pushing backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:back"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/random-jdr-backend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/random-jdr-backend:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-backend:buildcache,mode=max
