name: Reusable Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Se connecter au registre Docker de GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Construire et Pousser l'image Docker frontend
        uses: docker/build-push-action@v6
        with:
          context: {{ defaultContext }}:front
          push: true
          tags: random-jdr-frontend:${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construire et Pousser l'image Docker backend
        uses: docker/build-push-action@v6
        with:
          context: {{ defaultContext }}:back
          push: true
          tags: random-jdr-backend:${{ github.ref_name }}
