name: Build and push to registry then deploy to cluster

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

env:
  HELM_CHART: ./helm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Connecting to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building and pushing frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:front"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-frontend:buildcache,mode=max

      - name: Building and pushing backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:back"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/random-jdr-backend:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/random-jdr-backend:buildcache,mode=max

  helm-lint:
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Installation de Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.x'

      - name: Check configuration Helm
        run: helm lint ${{ env.HELM_CHART }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Installation de Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.x'

      - name: Déploiement de la charte Helm
        run: |
          helm upgrade --install random-jdr ${{ env.HELM_CHART }} \
            --set github.repository_owner=${{ github.repository_owner }} \
            --set github.tag=${{ github.ref_name }} \
            --namespace random-jdr --create-namespace
