name: Reusable Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v4

      - name: Se connecter au registre Docker de GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Construire et Pousser l'image Docker frontend
        uses: docker/build-push-action@v5
        with:
          context: front
          push: true
          tags: ghcr.io/random-jdr-frontend:${{ github.ref_name }}

      - name: Construire et Pousser l'image Docker backend
        uses: docker/build-push-action@v5
        with:
          context: back
          push: true
          tags: ghcr.io/random-jdr-backend:${{ github.ref_name }}
