name: Helm CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'helm/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm chart for production
        run: helm lint ./helm -f ./helm/values-prod.yaml

      - name: Lint Helm chart for staging
        run: helm lint ./helm -f ./helm/values-prod.yaml